# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: /blog/:year/:title.htm

show_excerpts: false

# Server
source: "."
destination: ./_gh_pages
host: 0.0.0.0
port: 9001
baseurl: ""
url: "http://help.afosto.com"
encoding: UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - nuget/
  - scss/
  - vendor/
  - CODE_OF_CONDUCT.md
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - README.md
  - sache.json
  - .idea

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Social
title: Afosto Application Documentation
email: support@afosto.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
github:             afosto
twitter:            afosto
twitter_url:        "https://twitter.com/afosto"
facebook:           afosto
facebook_url:       "https://www.facebook.com/afosto/"
social_image_path:  /assets/brand/afosto-social.jpg
social_logo_path:   /assets/brand/afosto-social-logo.jpg


afosto_url:         "https://afosto.com"
app_url:            "https://app.afosto.com"
pos_url:            "https://pos2.afosto.com"
github_url:         "https://github.com/afosto"
api_url:            "https://docs.afosto.com/"

toc:
  min_level:        2
  max_level:        4
